"""Configuration package for application settings and constants."""

from .constants import (
    DEFAULT_APP_HOST,
    DEFAULT_APP_PORT,
    DEFAULT_CHUNK_OVERLAP,
    DEFAULT_CHUNK_SIZE,
    DEFAULT_EMBEDDING_BATCH_SIZE,
    DEFAULT_EMBEDDING_DIMENSION,
    DEFAULT_EMBEDDING_MODEL,
    DEFAULT_EMBEDDING_PROVIDER,
    DEFAULT_LOG_FORMAT,
    DEFAULT_OPENROUTER_CHAT_MODEL,
    DEFAULT_PDF_EXTRACTOR,
    DEFAULT_PINECONE_NAMESPACE,
)
from .settings import Settings, get_settings

__all__ = [
    "DEFAULT_APP_HOST",
    "DEFAULT_APP_PORT",
    "DEFAULT_CHUNK_OVERLAP",
    "DEFAULT_CHUNK_SIZE",
    "DEFAULT_EMBEDDING_BATCH_SIZE",
    "DEFAULT_EMBEDDING_DIMENSION",
    "DEFAULT_EMBEDDING_MODEL",
    "DEFAULT_EMBEDDING_PROVIDER",
    "DEFAULT_LOG_FORMAT",
    "DEFAULT_OPENROUTER_CHAT_MODEL",
    "DEFAULT_PDF_EXTRACTOR",
    "DEFAULT_PINECONE_NAMESPACE",
    "Settings",
    "get_settings",
]
