"""Shared application constants."""

DEFAULT_EMBEDDING_PROVIDER = "sentence_transformers"
DEFAULT_EMBEDDING_MODEL = "sentence-transformers/all-MiniLM-L6-v2"
DEFAULT_EMBEDDING_DIMENSION = 384
DEFAULT_EMBEDDING_BATCH_SIZE = 32
DEFAULT_OPENROUTER_CHAT_MODEL = "meta-llama/llama-3.2-3b-instruct:free"
DEFAULT_PDF_EXTRACTOR = "pypdf"
DEFAULT_APP_HOST = "0.0.0.0"
DEFAULT_APP_PORT = 8000
DEFAULT_CHUNK_SIZE = 700
DEFAULT_CHUNK_OVERLAP = 60
DEFAULT_PINECONE_NAMESPACE = "contracts-dev"
DEFAULT_LOG_FORMAT = "json"
